# SPDX-License-Identifier: CC0-1.0
# SPDX-FileCopyrightText: 2022 Linaro Ltd.
# SPDX-FileCopyrightText: 2022 Viresh Kumar <viresh.kumar@linaro.org>

[package]
name = "libgpiod-sys"
version = "0.1.1"
authors = ["Viresh Kumar <viresh.kumar@linaro.org>"]
description = "libgpiod public header bindings"
repository = "https://git.kernel.org/pub/scm/libs/libgpiod/libgpiod.git"
categories = ["external-ffi-bindings", "os::linux-apis"]
rust-version = "1.78"
keywords = ["libgpiod", "gpio"]
license = "Apache-2.0 OR BSD-3-Clause"
edition = "2021"

exclude = [
    "Makefile.am",
]

[features]
v2_1 = []

[dependencies]

[build-dependencies]
bindgen = "0.63"
system-deps = "2.0"

[package.metadata.system-deps.libgpiod]
name = "libgpiod"
version = "2"
v2_1 = { version = "2.1" }
